Database_connection:
  oracle_bo: 'ttttt/11111@1.1.1.1/DB'
  postgresql: 'host=1.1.1.1 dbname=db user=ttttt password=11111 port=5432 connect_timeout=5'
elasticsearch:
  url: "http://1.1.1.1:9200"
  api_key: "11111"
Redis:
  port: 6379
  host: "1.1.1.1"
  password: "11111"

